//! The screenshots, and the card a shared link unfurls into.
//!
//! Generated by `node tools/build-site-assets.mjs` from
//! `crates/global-connect/artifacts`. Do not edit. The naming rule that put
//! each row here is in that folder's README, and the build refuses a file that
//! breaks it.
//!
//! Compiled in rather than served from a directory, like the stylesheet and for
//! the same two reasons: the site stays one artefact, and a table of known
//! names has no path to traverse.

/// One picture, and everything a page needs to draw it without reflowing.
pub struct Shot {
    /// Which application it belongs to - the part of the filename before the
    /// first hyphen. Empty for the social card, which belongs to none.
    pub app: &'static str,
    pub screen: &'static str,
    pub url: &'static str,
    pub bytes: &'static [u8],
    pub mime: &'static str,
    /// Its real dimensions, read out of the file at build time. Both reach the
    /// `<img>`, because one without the other is a page that reflows when the
    /// picture lands - worst on the slow connection this site is kind to.
    pub width: u32,
    pub height: u32,
}

/// Every screenshot, sorted by filename.
pub static SHOTS: &[Shot] = &[
    Shot {
        app: "inventory",
        screen: "items",
        url: "/assets/inventory-items.6b4f167182bd.png",
        bytes: include_bytes!("../assets/inventory-items.6b4f167182bd.png"),
        mime: "image/png",
        width: 2878,
        height: 940,
    },
];

/// The 1200x630 card, when `artifacts/og-image` exists.
pub static SOCIAL: Option<Shot> = None;

/// The handwriting face, when one has been dropped into `fonts/`.
pub static HANDWRITING: Option<(&str, &[u8])> = None;

impl Shot {
    /// Find every shot for one application, in filename order.
    pub fn of(app: &str) -> impl Iterator<Item = &'static Shot> {
        SHOTS.iter().filter(move |shot| shot.app == app)
    }
}
