//! Where the site's assets are, and what is in them.
//!
//! Generated by `node tools/build-site-assets.mjs`. Do not edit: the hash in
//! each URL is the hash of the file the script wrote, and changing one without
//! the other serves a page that points at nothing.
//!
//! The files' sizes are not published here, for the reason Desk's equivalent
//! gives: a constant nothing reads is a fact that stops being true quietly. The
//! script prints them when it runs, and that is where the claim in ADR 0007
//! about this site's weight should be checked.

/// The stylesheet's URL.
///
/// Named by [`base.html`](../templates/base.html) and answered by
/// [`crate::routes::stylesheet`]. The hash means a browser may keep it
/// forever, and that a changed stylesheet is a different address rather than a
/// stale copy.
pub const STYLESHEET: &str = "/assets/site.2d664dd5ceba.css";

/// The bytes themselves, compiled into the binary.
///
/// One artefact: copy the binary, run it. A static directory beside it is a
/// second thing to deploy and a second thing to get wrong.
pub const STYLESHEET_CSS: &str = include_str!("../assets/site.2d664dd5ceba.css");

/// The script's URL, hashed and cached the same way.
///
/// Everything it does is optional - see `script/site.js`. A page is complete
/// without it, which is what lets it be loaded `defer` and never waited on.
pub const SCRIPT: &str = "/assets/site.29d84c23724d.js";

pub const SCRIPT_JS: &str = include_str!("../assets/site.29d84c23724d.js");
